name:  bt4vs - Portable Build Tools for Visual Studio
run-name: ${{ github.actor }} Portable Build Tools for Visual Studio.
on:
  push:
    paths:
        - README.md

jobs:
  setup:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Download 
        run: curl -fL --retry 3 -o vs_BuildTools.exe https://aka.ms/vs/stable/vs_BuildTools.exe

      - name: Install chocolatey visualstudio2026-workload-vctools package
        run: .\vs_BuildTools.exe --quiet --wait --norestart --nocache --add Microsoft.VisualStudio.Workload.VCTools --installPath c:\home\programs\bt4vs --includeOptional --includeRecommended

      - name: Create package
        run: |
          New-Item -Path 'artifact' -ItemType Directory
          Compress-Archive -Path c:\home\programs\bt4vs -D artifact\bt4vs.zip
          
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag_name: ${{ github.ref }}
          name: bt4vs.${{ github.ref }}.zip
          artifacts: "artifact/bt4vs.zip"
