name:  bt4vs - Portable Build Tools for Visual Studio
run-name: ${{ github.actor }} Portable Build Tools for Visual Studio.
on:
  push:
    paths:
        - README.md

jobs:
  setup:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Download [ vs_BuildTools.exe ]
        run: curl -L -o vs_BuildTools.exe https://aka.ms/vs/stable/vs_BuildTools.exe
      - name: Create layout
        run: |
          $p = Start-Process -FilePath .\vs_BuildTools.exe -Wait -PassThru -ArgumentList `
          '--layout','D:\vs2026-layout','--lang','en-US',
          '--add','Microsoft.VisualStudio.Component.VC.Tools.x86.x64',
          '--add Microsoft.VisualStudio.Component.Windows11SDK.22621',
          '--includeRecommended'
          if ($p.ExitCode -notin 0,3010) { exit $p.ExitCode }
      - name: Run installation
        run: |
          $p = Start-Process -FilePath D:\vs2026-layout\vs_BuildTools.exe -Wait -PassThru -ArgumentList `
          '--quiet','--wait','--norestart','--noweb',
          '--installPath','D:\bt4vs',
          '--add','Microsoft.VisualStudio.Component.VC.Tools.x86.x64',
          '--add Microsoft.VisualStudio.Component.Windows11SDK.22621',
          '--includeRecommended'
          if ($p.ExitCode -notin 0,3010) { exit $p.ExitCode }
      - name: Create package
        run: |
          New-Item -Path 'artifact' -ItemType Directory
          Compress-Archive -Path D:\bt4vs -D artifact\bt4vs.zip     
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag_name: ${{ github.ref }}
          name: bt4vs.${{ github.ref }}.zip
          artifacts: "artifact/bt4vs.zip"

