name:  bt4vs - Portable Build Tools for Visual Studio
run-name: ${{ github.actor }} Portable Build Tools for Visual Studio.
on:
  push:
    paths:
        - README.md

jobs:
  setup:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Download [ vs_BuildTools.exe ]
        run: curl -o vs_BuildTools.exe https://aka.ms/vs/stable/vs_BuildTools.exe

